---
title: "Tidying Consumer Data"
author: "Alana"
date: "12/9/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate) #Don't think I'll be needing lubridate but leaving it in for now
library(tidyxl)
library(data.table)
library(unpivotr)
library(knitr)
```

# Testing the method for reading in the data and cleaning

```{r }
#Testing out the more technical solution!

# Each cell in the excel file becomes an entire row in R
all_cells <- tidyxl::xlsx_cells("May 2019_edited.xlsx")


#Filter non-blank rows, select variables
all_cells <- all_cells %>%
  dplyr::filter(!is_blank) %>%
  select(row, col, data_type, character, numeric)

tidier <- all_cells %>%
  behead("up-left", consumption) %>%
  behead("up", type) %>%
  behead("left-up", question)%>%
  behead("left", demographic) %>%
  rename(n= numeric) %>%
  select(-data_type, -row, -col, -character)

#Removing survey totals from dataframe and creating percentage column
tidied_data <- tidier[-c(1:2), ] %>%
  mutate(percentage = mean(n, na.rm= TRUE))
  

```

#Applying base method to relevant sheets 

I tried to write a 'for' loop to do this, but it kept throwing me errors,
so I unfortunately have to do it the old fashioned way: by reading in each individual
sheet and performing the cleaning and tidying functions manually for each one...


``` {r, Reading in other sheets}

raw <- tidyxl::xlsx_cells(path = "International Cuisine Tracker - US - May 2021 - Databook(AutoRecovered).xlsx", sheet = c("May 2019":"May 2021"))


raw_August2019 <- tidyxl::xlsx_cells(path = "International Cuisine Tracker - US - May 2021 - Databook(AutoRecovered).xlsx", sheet = "August 2019")

raw_August2019 <- raw_August2019 %>%
  dplyr::filter(!is_blank) %>%
  select(row, col, data_type, character, numeric)

clean_August2019 <- raw_August2019 %>%
  behead("up-left", consumption) %>%
  behead("up", type) %>%
  behead("left-up", question)%>%
  behead("left", demographic) %>%
  rename(n= numeric) %>%
  select(-data_type, -row, -col, -character)



```

```{r}

#Testing analytic capabilities of newly formatted data

tidied_data %>%
  group_by(type) %>%
  mutate(percentage = mean(n, na.rm= TRUE)) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  ggplot(aes(x = demographic, y = percentage, fill = type)) + 
  geom_col(color = "black") + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_linedraw()+
  labs(title = "Ethnic Food Consumption Across Racial Categories", 
       subtitle = "May 2019 Survey", 
       x = "Race",
       y = "Percent %",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

#Visualizing any consumption across racial groups
tidied_data %>%
  group_by(type) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  filter(consumption == "Any consumption (net)") %>%
  ggplot(aes(x = demographic, y = n, fill = type)) + 
  geom_col(color = "black") + 
  theme_linedraw()+
  labs(title = "Any Ethnic Food Consumption Across Racial Categories", 
       subtitle = "May 2019 Survey", 
       x = "Race",
       y = "Count (out of 2000 respondents)",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

# Visualizing at take-out consumption
tidied_data %>%
  group_by(type) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  filter(consumption == "Away from home (eg restaurant, café, etc)") %>%
  ggplot(aes(x = demographic, y = n, fill = type)) + 
  geom_col(color = "black") + 
  theme_linedraw()+
  labs(title = "Any Ethnic Food Consumption Across Racial Categories", 
       subtitle = "May 2019 Survey", 
       x = "Race",
       y = "Count (out of 2000 respondents)",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")


# Visualizing at take-out consumption
tidied_data %>%
  group_by(type) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  filter(consumption == "At home") %>%
  ggplot(aes(x = demographic, y = n, fill = type)) + 
  geom_col(color = "black") + 
  theme_linedraw()+
  labs(title = "Any Ethnic Food Consumption Across Racial Categories", 
       subtitle = "May 2019 Survey", 
       x = "Race",
       y = "Count (out of 2000 respondents)",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

```
