---
title: "Empirical Paper"
author: "Alana"
date: "11/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
library(tidyxl)
libraru(glue)

#Reading in the data 

file <- read_csv("International Cuisine Tracker - US - May 2021 - Databook.xlsx")

```

```{r}

# Here, I will test methods of extracting info and tidying before creating a function: 

#Reading in a sheet from the original dataset 
raw_data <- xlsx_cells("International Cuisine Tracker - US - May 2021 - Databook.xlsx",  sheet = 2)

#Isolating cuisine types from sheet
cuisine <- raw_data %>%
  filter(row == 37, !is.na(character)) %>%
  select(sheet, col, cuisine_type = character)

# Finding the stats per cuisine per type of dining experience

find_cuisine_stat_any <- function(df, col4, col32) {
  df %>%
    filter((col == {{col4}} | col == {{col32}}) & row > 38) %>%
    select(sheet, c(row:col), c(numeric))
}

find_cuisine_stat_any(raw_data, col4, col32)


expanded_data <- cuisines %>%
  pivot_wider(names_from = "Mintel Emerging International Cuisine Tracker")



```
