---
title: "Exploratory Data Visualizations"
author: "Alana LaBelle-Hahn"
date: "12/10/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readxl)
library(tidyxl)
library(data.table)
library(unpivotr)
library(knitr)
library(stringr) 
library(zoo)

```

```{r, reading in data}

# Loading in the data
consumer_data <- read_csv("combined_months.csv") 

# For some reason, R read in the date column as a character string so here I am
#converting everything back over to numeric...
consumer_data$date <- as.yearmon(paste(consumer_data$year, 
                                       consumer_data$month), "%Y %m")

#Attempt to try and standardize demographic response categories and remove excel position labels

consumer_data <- consumer_data %>%
  transform(demographic = substr(demographic,1,nchar(demographic)-4))



```

```{r}

# I want to create cuisine groups in order to visualize the difference between ethnic food categories

## A group for Asian "perceived" restaurants. Those whose food may associated with 
## certain phenotypes
asian_perceived <- consumer_data %>%
  filter(type == c("chinese", "japanese", "thai", 
                   "vietnamese", "korean", "filipino"))


#A group for non Asian "perceived" cuisines
non_asian_perceived <- consumer_data %>%
  filter(type == c("moroccan", "african", "latin", 
                   "greek", "middle eastern", "mexican"))


```




```{r}
# Visualizing differences between cuisine categories

asian_perceived %>%
  group_by(type) %>%
  filter(consumption == "Away from home (eg restaurant, café, etc)") %>%
  ggplot(mapping= aes(x = date, y = n, fill = n)) + 
  geom_col() +
  coord_flip() +
  scale_color_brewer(palette="Dark2") +
  facet_wrap(facets = vars(type), scales = "free") + 
  labs(title = "Consumption of Asian-perceived Cuisines",
       subtitle = "Before and throughout the pandemic",
       y = "count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")


#Replicating the affect with non_Asian perceived

non_asian_perceived %>%
  group_by(type) %>%
  filter(consumption == "Away from home (eg restaurant, café, etc)") %>%
  ggplot(mapping= aes(x = date, y = n, fill = n)) + 
  geom_col() +
  coord_flip() +
  scale_color_brewer(palette="Dark2") +
  facet_wrap(facets = vars(type), scales = "free") + 
  labs(title = "Consumption of non Asian-perceived Cuisines ",
       subtitle = "Before and Throughout Pandemic",
       y = "count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

```


```{r, fig.height = 9, fig.width = 12}

#Seeing all the comparisons in panel form - *VERY USEFUL*
consumer_data %>%
  group_by(type) %>%
  filter(consumption == "Away from home (eg restaurant, café, etc)") %>%
  filter(!type == "none of the above") %>%
  filter(!type == "None of the above") %>%
  ggplot(mapping= aes(x = date, y = n, fill = n, na.rm = TRUE)) + 
  geom_col() +
  coord_flip() +
  ylim(0,10000) +
  scale_color_brewer(palette="Dark2") +
  facet_wrap(facets = vars(type), scales = "free") + 
  labs(title = "Consumption Levels Across Ethnic Cuisines ",
       subtitle = "Before and Throughout Pandemic",
       y = "count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

```


# A USABLE GRAPH!

```{r, echo = FALSE}
#Testing analytic capabilities of newly formatted data

consumer_data %>%
  group_by(type) %>%
  group_by(date) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  filter(!type == "none of the above") %>%
  filter(!type == "None of the above") %>%
  filter(date == "February 2020") %>%
  ggplot(aes(x = demographic, y = n, fill = type, na.rm = TRUE)) + 
  geom_col(width = .5) + 
  #scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_linedraw()+
  labs(title = "Ethnic Food Consumption Across Racial Categories", 
       subtitle = "Online Survey of 2000 Adults in February 2020", 
       x = "Race",
       y = "Count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")


# Doing a comparison to immediately after the start of the pandemic (May 2020)

consumer_data %>%
  group_by(type) %>%
  group_by(date) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  filter(!type == "none of the above") %>%
  filter(!type == "None of the above") %>%
  filter(date == "May 2020") %>%
  ggplot(aes(x = demographic, y = n, fill = type, na.rm = TRUE)) + 
  geom_col(width = .5) + 
  #scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_linedraw()+
  labs(title = "Ethnic Food Consumption Across Racial Categories", 
       subtitle = "Online Survey of 2000 Adults in May 2020", 
       x = "Race",
       y = "Count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

#Comparing to August 2020 when we were well into the pandemic

consumer_data %>%
  group_by(type) %>%
  group_by(date) %>%
  filter(question == "Race (4 race groups):") %>%
  filter(!consumption == "Total") %>%
  filter(!type == "none of the above") %>%
  filter(!type == "None of the above") %>%
  filter(date == "August 2020") %>%
  ggplot(aes(x = demographic, y = n, fill = type, na.rm = TRUE)) + 
  geom_col(width = .5) + 
  #scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_linedraw()+
  labs(title = "Ethnic Food Consumption Across Racial Categories", 
       subtitle = "Online Survey of 2000 Adults in August 2020", 
       x = "Race",
       y = "Count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")

```


```{r, By Census Region}

# Attempting to plot comparison across census region

consumer_data %>%
  group_by(type) %>%
  filter(consumption == "Away from home (eg restaurant, café, etc)") %>%
  filter(!type == "none of the above") %>%
  filter(!type == "None of the above") %>%
  filter(type == c("chinese", "japanese", "thai", 
                   "vietnamese", "korean", "filipino")) %>%
  filter(!consumption == "Total") %>%
  filter(question == "Census region:") %>%
  str_sub(consumer_data$demographic,1,nchar(consumer_data$demographic)-4) %>%
  ggplot(mapping = aes(x = demographic, y = n, fill = type, na.rm = TRUE)) +
  geom_col()


  
    ggplot(mapping = aes(x = date, fill = demographic, na.rm = TRUE)) + 
  geom_violin(fill = n) +
  labs(title = "Consumption of Asian foods across Census REgions",
       subtitle = "Before and Throughout Pandemic",
       x = "Monthly Percentages Aggregated",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")
    
    
```


``` {r}
%>%
  ggplot(mapping= aes(x = date, y = n, na.rm = TRUE)) + 
  geom_col() +
  coord_flip() +
  ylim(0,10000) +
  scale_color_brewer(palette="Dark2") +
  facet_wrap(facets = vars(demographic), scales = "free")

+ 
  labs(title = "Consumption Levels Across Ethnic Cuisines ",
       subtitle = "Before and Throughout Pandemic",
       y = "count",
       caption = "Source: https://reports-mintel-com.proxy.uchicago.edu/display/1044545/?fromSearch=%3Ff
       ilters.category%3D118%26last_filter%3Dcategory")
```

